# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 01:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20170528_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='cnt',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Единична цена'),
        ),
    ]
