# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Основен'),
        ),
    ]
