# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_auto_20170529_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
