# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0004_auto_20170529_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Адрес'),
        ),
    ]
