# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170609_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='child',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дете'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=400, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=12000, null=True, verbose_name='Забележка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes_kitchen',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Забележка за кухнята'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes_torta',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Забележка за тортата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Родител'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
