# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 01:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0005_auto_20170529_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Доставна цена'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Продажна цена'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Име'),
        ),
    ]
