# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestore',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата на създаване'),
        ),
        migrations.AddField(
            model_name='articlestore',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата на промяна'),
        ),
        migrations.AddField(
            model_name='articlestore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Служител'),
        ),
        migrations.AlterField(
            model_name='articlestore',
            name='cnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Налично кол.'),
        ),
        migrations.AlterField(
            model_name='articlestore',
            name='cnt_bl',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Блокирано кол.'),
        ),
        migrations.AlterField(
            model_name='articlestore',
            name='cnt_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Минимално кол.'),
        ),
        migrations.AlterField(
            model_name='stock_acceptance_detail',
            name='cnt',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stock_delivery_detail',
            name='cnt',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Количество'),
        ),
    ]
