# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170528_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Забележка за блокировката'),
        ),
    ]
