# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 01:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170529_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='cnt_bl',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Блокирано кол.'),
        ),
        migrations.AlterField(
            model_name='articlestore',
            name='cnt_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Минимално кол.'),
        ),
        migrations.AlterField(
            model_name='stock_acceptance_detail',
            name='cnt',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stock_delivery_detail',
            name='cnt',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество'),
        ),
    ]
