# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-02 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170620_0441'),
    ]

    operations = [
        migrations.RunSQL("""CREATE OR REPLACE VIEW public.article_store_min AS
                                select article_store.*,
                                       CNT_MIN - CNT under_cnt
                                from article_store
                                  where CNT_MIN - CNT  > 0;
                           """)
    ]
