# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 18:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ostrovaweb.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('schedule_date', models.DateField(blank=True, max_length=40, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Календари',
                'verbose_name': 'Календар',
                'managed': False,
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Име')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('delivery_price', models.FloatField(blank=True, null=True, verbose_name='Доставна цена')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='Продажна цена')),
                ('last_price_dl', models.FloatField(blank=True, null=True, verbose_name='Посл.Цена на доставка')),
                ('last_price_sl', models.FloatField(blank=True, null=True, verbose_name='Посл.Цена на продажба')),
                ('last_update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата промяна')),
                ('measure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мярка')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name_plural': 'Артикули',
                'verbose_name': 'Артикул',
                'managed': True,
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(max_length=80, verbose_name='Име')),
                ('delivery_type', models.BooleanField(default=False, verbose_name='За доставки')),
                ('order_type', models.BooleanField(default=False, verbose_name='За продажби')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на създаване')),
            ],
            options={
                'verbose_name_plural': 'Артикулни групи',
                'verbose_name': 'Артикулна група',
                'managed': True,
                'db_table': 'article_group',
            },
        ),
        migrations.CreateModel(
            name='Cashdesk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('rec_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('beg_bank_100', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 100')),
                ('beg_bank_50', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 50')),
                ('beg_bank_20', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 20')),
                ('beg_bank_10', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 10')),
                ('beg_bank_5', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 5')),
                ('beg_bank_2', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 2')),
                ('beg_coin_100', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 100')),
                ('beg_coin_50', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 50')),
                ('beg_coin_20', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 20')),
                ('beg_coin_10', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 10')),
                ('beg_coin_5', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 5')),
                ('beg_close_date', models.DateField(blank=True, null=True, verbose_name='Дата на предаване')),
                ('beg_open_date', models.DateField(blank=True, null=True, verbose_name='Дата на приемане')),
                ('end_bank_100', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 100')),
                ('end_bank_50', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 50')),
                ('end_bank_20', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 20')),
                ('end_bank_10', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 10')),
                ('end_bank_5', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 5')),
                ('end_bank_2', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 2')),
                ('end_coin_100', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 100')),
                ('end_coin_50', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 50')),
                ('end_coin_20', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 20')),
                ('end_coin_10', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 10')),
                ('end_coin_5', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 5')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на създавне')),
                ('last_update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на промяна')),
                ('beg_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beg_close', to=settings.AUTH_USER_MODEL, verbose_name='Предал')),
                ('beg_open', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beg_open', to=settings.AUTH_USER_MODEL, verbose_name='Приел')),
            ],
            options={
                'verbose_name_plural': 'Каси',
                'verbose_name': 'Каса',
                'managed': True,
                'db_table': 'cashdesk',
            },
            bases=(ostrovaweb.utils.AdminURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cashdesk_detail_expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Забележка')),
                ('amount', models.FloatField(verbose_name='Сума')),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Cashdesk', verbose_name='Каса')),
            ],
            options={
                'verbose_name_plural': 'Разходни касови ордери',
                'verbose_name': 'Разходен касов ордер',
                'managed': True,
                'db_table': 'cashdesk_detail_expense',
            },
        ),
        migrations.CreateModel(
            name='Cashdesk_detail_income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Забележка')),
                ('amount', models.FloatField(verbose_name='Сума')),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Cashdesk', verbose_name='Каса')),
            ],
            options={
                'verbose_name_plural': 'Приходни касови ордери',
                'verbose_name': 'Приходен касов ордер',
                'managed': True,
                'db_table': 'cashdesk_detail_income',
            },
        ),
        migrations.CreateModel(
            name='Cashdesk_groups_expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Група')),
                ('sub_name', models.CharField(blank=True, max_length=120, verbose_name='Подгрупа')),
            ],
            options={
                'verbose_name_plural': 'Групи каса разход',
                'verbose_name': 'Група каса разход',
                'managed': True,
                'db_table': 'cashdesk_groups_expense',
            },
        ),
        migrations.CreateModel(
            name='Cashdesk_groups_income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Група')),
                ('sub_name', models.CharField(blank=True, max_length=120, verbose_name='Подгрупа')),
            ],
            options={
                'verbose_name_plural': 'Групи каса приход',
                'verbose_name': 'Група каса приход',
                'managed': True,
                'db_table': 'cashdesk_groups_income',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=240, verbose_name='Име')),
                ('hall_price', models.FloatField(blank=True, null=True, verbose_name='Цена на зала')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Клубове',
                'verbose_name': 'Клуб',
                'managed': True,
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата на заявка')),
                ('status', models.CharField(blank=True, choices=[('ПОРЪЧАНO', 'ПОРЪЧАНO'), ('ДОСТАВЕНО', 'ДОСТАВЕНО'), ('ОТКАЗАНО', 'ОТКАЗАНО')], max_length=80, verbose_name='Статус')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата на доставка ')),
                ('invoice_no', models.CharField(blank=True, max_length=400, verbose_name='Номер на фактура')),
                ('firm_invoice_no', models.CharField(blank=True, max_length=400, verbose_name='Факт. На фирма:')),
                ('paid', models.CharField(blank=True, choices=[('ДА', 'ДА'), ('НЕ', 'НЕ')], max_length=80, verbose_name='Платено')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Забележка')),
                ('delivery_amount', models.FloatField(blank=True, null=True, verbose_name='Крайна цена')),
                ('last_update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на опресняване')),
                ('cashdesk_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Cashdesk', verbose_name='Дата на плащане')),
                ('club_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name_plural': 'Доставки',
                'verbose_name': 'Доставка',
                'managed': True,
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('cnt', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Единична цена')),
                ('price_actual', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('goods_id', models.IntegerField(blank=True, null=True, verbose_name='Номер на стока')),
                ('article_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Article', verbose_name='Артикул')),
                ('delivery_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Delivery', verbose_name='Доставка N')),
                ('group_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.ArticleGroup', verbose_name='Артикулна група')),
            ],
            options={
                'verbose_name_plural': 'Доставки описание',
                'verbose_name': 'Доставка описание',
                'managed': True,
                'db_table': 'delivery_detail',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('rec_date', models.DateField(blank=True, null=True, verbose_name='Дата на р.д.')),
                ('rec_time_slot', models.IntegerField(blank=True, null=True, verbose_name='Слот')),
                ('rec_time', models.CharField(blank=True, max_length=80, verbose_name='Начало')),
                ('rec_time_end', models.CharField(blank=True, max_length=40, verbose_name='Край')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('parent', models.CharField(blank=True, max_length=240, verbose_name='Родител')),
                ('child', models.CharField(blank=True, max_length=200, verbose_name='Дете')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Години')),
                ('child_count', models.IntegerField(blank=True, null=True, verbose_name='Брой деца')),
                ('adult_count', models.IntegerField(blank=True, null=True, verbose_name='Брой възрастни')),
                ('hall_count', models.IntegerField(blank=True, null=True, verbose_name='Брой зала')),
                ('hall_price', models.FloatField(blank=True, null=True, verbose_name='Цена на зала')),
                ('deposit', models.FloatField(blank=True, null=True, verbose_name='Капаро')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Отстъпка')),
                ('price_final', models.FloatField(blank=True, null=True, verbose_name='Крайна цена')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='Дата на капаро')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата на плащане')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Дата на валидност')),
                ('refusal_date', models.DateField(blank=True, null=True, verbose_name='Дата на отказ')),
                ('refusal_reason', models.CharField(blank=True, max_length=400, verbose_name='Причина за отказ')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата на поръчка')),
                ('notes', models.TextField(blank=True, max_length=12000, verbose_name='Забележка')),
                ('address', models.CharField(blank=True, max_length=1024, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=400, verbose_name='E-mail')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на създаване')),
                ('last_update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на промяна')),
                ('changes', models.TextField(blank=True, max_length=12000, verbose_name='Промени')),
                ('deposit2', models.FloatField(blank=True, null=True, verbose_name='Капаро 2')),
                ('deposit2_date', models.DateField(blank=True, null=True, verbose_name='Дата на капаро2')),
                ('update_state', models.CharField(blank=True, max_length=80, verbose_name='Актуализация на състоянието')),
                ('locked', models.CharField(blank=True, max_length=4, verbose_name='Статус за приключване')),
                ('payed_final', models.FloatField(blank=True, null=True, verbose_name='Финално плащане')),
                ('notes_torta', models.TextField(blank=True, max_length=2000, verbose_name='Забележка за тортата')),
                ('notes_kitchen', models.TextField(blank=True, max_length=2000, verbose_name='Забележка за кухнята')),
                ('club_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name_plural': 'Поръчки',
                'verbose_name': 'Поръчка',
                'managed': True,
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('cnt', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Единична цена')),
                ('article_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Article', verbose_name='Артикул')),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.ArticleGroup', verbose_name='Артикулна група')),
                ('order_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Order', verbose_name='Поръчка N')),
            ],
            options={
                'verbose_name_plural': 'Поръчки описание',
                'verbose_name': 'Поръчка описание',
                'managed': True,
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Име')),
                ('club_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name_plural': 'Салони',
                'verbose_name': 'Салон',
                'db_table': 'saloon',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=400, verbose_name='Име')),
                ('price_actual', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата на Поръчка')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата на доставка ')),
                ('type', models.CharField(blank=True, max_length=40, verbose_name='Тип')),
                ('article_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Article', verbose_name='Артикул')),
                ('club_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Club', verbose_name='Клуб')),
                ('cnt_del_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.DeliveryDetail', verbose_name='дост.к-во')),
                ('cnt_or_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.OrderDetail', verbose_name='пор.к-во')),
            ],
            options={
                'verbose_name_plural': 'Складове',
                'verbose_name': 'Склад',
                'managed': True,
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Име')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Доставчици',
                'verbose_name': 'Доставчик',
                'managed': True,
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('time_slot', models.IntegerField(blank=True, null=True, verbose_name='Часови сегмент')),
                ('time', models.CharField(blank=True, max_length=40, verbose_name='Начало')),
                ('time_end', models.CharField(blank=True, max_length=40, verbose_name='Край')),
                ('weekday', models.IntegerField(blank=True, null=True, verbose_name='Ден от седмицата')),
            ],
            options={
                'verbose_name_plural': 'Часове',
                'verbose_name': 'Час',
                'managed': True,
                'db_table': 'times',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='saloon_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Saloon', verbose_name='Салон за възрастни'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Служител'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Supplier', verbose_name='Доставчик'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Служител'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_income',
            name='cashdesk_groups_income_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Cashdesk_groups_income', verbose_name='Група каса приходи'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_income',
            name='delivery_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Delivery', verbose_name='Плащане по доставка'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_expense',
            name='cashdesk_groups_expense_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Cashdesk_groups_expense', verbose_name='Групи каса разходи'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_expense',
            name='order_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Order', verbose_name='Плащане по поръчка'),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='club_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Club', verbose_name='Обект'),
        ),
        migrations.AddField(
            model_name='article',
            name='group_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.ArticleGroup', verbose_name='Артикулна група'),
        ),
    ]
