# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostrovaCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True, 'verbose_name': 'Календар', 'verbose_name_plural': 'Календари'},
        ),
    ]
