# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostrovaCalendar', '0002_auto_20170420_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('schedule_date', models.DateField(blank=True, max_length=40, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Календари',
                'verbose_name': 'Календар',
                'managed': True,
                'db_table': 'schedule',
            },
        ),    
        migrations.AddField(
            model_name='schedule',
            name='club_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='order_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Order', verbose_name='Поръчка N'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='times_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ostrovaCalendar.Times', verbose_name='Часови сегмент'),
            preserve_default=False,
        ),
    ]
