# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubesviewer', '0002_auto_20160528_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubesview',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
