# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubesviewer', '0003_auto_20170528_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cubesview',
            options={'ordering': ['name'], 'verbose_name': 'Записан Изглед за Куб', 'verbose_name_plural': 'Записани изгледи за кубове'},
        ),
        migrations.AlterField(
            model_name='cubesview',
            name='data',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cubesview',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='cubesview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Собсвеник'),
        ),
        migrations.AlterField(
            model_name='cubesview',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='Споделено'),
        ),
    ]
