# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubesviewer', '0004_auto_20170620_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cubesview',
            options={'ordering': ['name'], 'permissions': (('view_olap_reports', 'Достъп до OLAP справките'),), 'verbose_name': 'Записан Изглед за Куб', 'verbose_name_plural': 'Записани изгледи за кубове'},
        ),
    ]
