# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rec_time_slot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_state',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'ЗАЯВЕНА'), ('CONFIRMED', 'ПОТВЪРДЕНА'), ('ORDERED', 'ПОРЪЧАНА'), ('CANCELED', 'ОТКАЗАНА')], default='REQUIRED', max_length=80, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата на създаване'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Отстъпка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rec_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 28, 21, 13, 27, 56787), verbose_name='Дата на р.д.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='rec_time',
            field=models.CharField(max_length=80, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rec_time_end',
            field=models.CharField(max_length=40, verbose_name='Край'),
        ),
        migrations.AlterField(
            model_name='order',
            name='saloon_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Saloon', verbose_name='Салон за възрастни'),
        ),
    ]
