# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170528_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rec_time',
            field=models.TimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rec_time_end',
            field=models.TimeField(verbose_name='Край'),
        ),
    ]
