# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170528_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Общо'),
        ),
    ]
