# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170609_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hall_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hall_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='validity_date',
        ),
    ]
