# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170620_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refusal_reason',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Причина за отказ'),
        ),
    ]
